name: Build FDUtilities
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            java: [ 17 ]
        fail-fast: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build……
        run: ./gradlew build
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
